/**
 * The owner's GLOBAL CONTENT RULES — GENERATED from
 * prompts/_global-content-rules.md by scripts/gen-prompt-template.py
 * (repo root). Single source of truth for the owner's absolute image ban
 * (no living beings, no faces, no body parts — even on objects).
 *
 * Every prompt template embeds this block (the script refuses to bundle a
 * prompt without it), and renderTemplate() appends it as a safety net to
 * any rendered prompt whose template somehow lost it. Regenerate after
 * editing the .md source:
 *
 *     python3 scripts/gen-prompt-template.py
 */

export const GLOBAL_CONTENT_RULES: string = "## GLOBAL CONTENT RULES \u2014 the owner's absolute image ban (every mission, every image)\n\nThese are the owner's personal life rules for image generation. They apply to EVERY image\nof EVERY mission on EVERY platform, and they override everything else \u2014 the mission brief,\nthe platform's rules, the demand research, anything below. When the brief or the research\nconflicts with them, THESE RULES WIN: pick the closest compliant subject, deliver it, and\nreport the adaptation. A violating image is rejected at the visual check and never saved.\n\n1. **NO LIVING BEINGS.** Never generate humans or animals \u2014 no mammals, birds, fish,\n   insects, reptiles or any other creature, real or fictional, cute or scary \u2014 not as\n   photos, not as illustrations or cartoons, not as silhouettes, shadows or reflections,\n   and not as toys, plushes, statues or figurines of living beings. Plants, flowers and\n   trees ARE allowed (they are not \"beings\" here), and so are food, objects, vehicles,\n   machines, buildings, interiors, landscapes, textures, patterns and abstracts \u2014 pick\n   those instead.\n2. **NO FACES \u2014 ZERO TOLERANCE, EVEN ON OBJECTS.** Nothing in any image may have, resemble\n   or evoke a face: no eyes, no ears, no mouth, no nose, no eyebrows, no face-like\n   patterns. This bans anthropomorphic designs (a smiling sun, a car with eyes, a happy\n   teapot, a jack-o'-lantern), statues, busts, mannequins, dolls, robots, masks, skulls,\n   carved or painted faces on any object, and pareidolia (clouds, wood knots, rocks or\n   shadows that \"look like\" a face). If a viewer could say \"this looks like a face\", the\n   image is REJECTED.\n3. **NO BODY PARTS \u2014 ZERO TOLERANCE, EVEN ON OBJECTS.** Nothing in any image may have,\n   resemble or evoke body parts: no hands, no feet, no arms, no legs, no fingers, no toes\n   \u2014 not attached to a subject, not isolated, not in close-up (a hand holding a cup, a\n   footprint, a fingerprint), and no object given limbs or hands.\n\nApply them at EVERY stage of the work. During the internet research, filter every trend,\ntheme and subject idea through these rules BEFORE planning anything \u2014 a living-beings\ntheme (farm animals, dinosaurs, ocean life, jungle friends, people, characters\u2026) is\nforbidden however well it sells; translate the demand into the closest non-living theme\n(vehicles, machines, buildings, toys, objects, plants, patterns\u2026). In EVERY generation\nprompt, include the negatives `no people, no animals, no living beings, no faces, no\nfacial features, no body parts, no anthropomorphic elements`. And at the visual check,\nreject any image where a living being, a face or a body part appears \u2014 even partially,\neven in the background, even cute or stylized.\n";
